name: Sanity CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install Dependencies
        run: yarn --frozen-lockfile

      - name: Install Sanity CLI
        run: npm i -g @sanity/cli

      - name: Deploy Sanity
        run: SANITY_AUTH_TOKEN="${{ secrets.SANITY_AUTH_TOKEN }}" yarn sanity deploy
